//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASPL.SharePoint2010.Layouts.ASPL.SharePoint2010 {
    
    
    public partial class AccessDeniedView {
    }
}
