//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCSAdvancedAlerts {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ListAndFieldNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ListAndFieldNames() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CCSAdvancedAlerts.ListAndFieldNames", typeof(ListAndFieldNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FromAddress.
        /// </summary>
        internal static string settingsListFromAddressFieldName {
            get {
                return ResourceManager.GetString("settingsListFromAddressFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ItemID.
        /// </summary>
        internal static string settingsListItemIdFieldName {
            get {
                return ResourceManager.GetString("settingsListItemIdFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ListID.
        /// </summary>
        internal static string settingsListListIdFieldName {
            get {
                return ResourceManager.GetString("settingsListListIdFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BodyTemplate.
        /// </summary>
        internal static string settingsListMailBpdyFieldName {
            get {
                return ResourceManager.GetString("settingsListMailBpdyFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CCSAdvancedAlertsList.
        /// </summary>
        internal static string settingsListName {
            get {
                return ResourceManager.GetString("settingsListName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MailSubject.
        /// </summary>
        internal static string settingsListSubjectFieldName {
            get {
                return ResourceManager.GetString("settingsListSubjectFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ToAddress.
        /// </summary>
        internal static string settingsListToAddressFieldName {
            get {
                return ResourceManager.GetString("settingsListToAddressFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebID.
        /// </summary>
        internal static string settingsListWebIdFieldName {
            get {
                return ResourceManager.GetString("settingsListWebIdFieldName", resourceCulture);
            }
        }
    }
}
