//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCSAdvancedAlerts {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ListAndFieldNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ListAndFieldNames() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CCSAdvancedAlerts.ListAndFieldNames", typeof(ListAndFieldNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        internal static string createdBy {
            get {
                return ResourceManager.GetString("createdBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert.
        /// </summary>
        internal static string DelayedAlertLookupFieldName {
            get {
                return ResourceManager.GetString("DelayedAlertLookupFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body.
        /// </summary>
        internal static string DelayedBodyFieldName {
            get {
                return ResourceManager.GetString("DelayedBodyFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EventType.
        /// </summary>
        internal static string DelayedEventTypeFieldName {
            get {
                return ResourceManager.GetString("DelayedEventTypeFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CCSAdvancedDelayedAlerts.
        /// </summary>
        internal static string DelayedListName {
            get {
                return ResourceManager.GetString("DelayedListName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ItemID.
        /// </summary>
        internal static string DelayedParentItemID {
            get {
                return ResourceManager.GetString("DelayedParentItemID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        internal static string DelayedSubjectFieldName {
            get {
                return ResourceManager.GetString("DelayedSubjectFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HighLightUpdatedFields.
        /// </summary>
        internal static string MTListHighLightUpdatedFieldsFieldName {
            get {
                return ResourceManager.GetString("MTListHighLightUpdatedFieldsFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InsertAttachments.
        /// </summary>
        internal static string MTListInsertAttachmentsFieldName {
            get {
                return ResourceManager.GetString("MTListInsertAttachmentsFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InsertUpdatedFields.
        /// </summary>
        internal static string MTListInsertUpdatedFieldsFieldName {
            get {
                return ResourceManager.GetString("MTListInsertUpdatedFieldsFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body.
        /// </summary>
        internal static string MTListMailBodyFieldName {
            get {
                return ResourceManager.GetString("MTListMailBodyFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        internal static string MTListMailSubjectFieldName {
            get {
                return ResourceManager.GetString("MTListMailSubjectFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CCSAdvancedAlertsMailTemplates.
        /// </summary>
        internal static string MTListName {
            get {
                return ResourceManager.GetString("MTListName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner.
        /// </summary>
        internal static string MTListOwnerFieldName {
            get {
                return ResourceManager.GetString("MTListOwnerFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert.
        /// </summary>
        internal static string MTUAlertFieldName {
            get {
                return ResourceManager.GetString("MTUAlertFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EventType.
        /// </summary>
        internal static string MTUEventTypeFieldName {
            get {
                return ResourceManager.GetString("MTUEventTypeFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HighLightUpdatedFields.
        /// </summary>
        internal static string MTUHighLightUpdatedFieldsFieldName {
            get {
                return ResourceManager.GetString("MTUHighLightUpdatedFieldsFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InsertAttachments.
        /// </summary>
        internal static string MTUInsertAttachmentsFieldName {
            get {
                return ResourceManager.GetString("MTUInsertAttachmentsFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InsertUpdatedFields.
        /// </summary>
        internal static string MTUInsertUpdatedFieldsFieldName {
            get {
                return ResourceManager.GetString("MTUInsertUpdatedFieldsFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CCSAdvancedTemplateForAlert.
        /// </summary>
        internal static string MTUListName {
            get {
                return ResourceManager.GetString("MTUListName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShareTemplateWithAllUsers.
        /// </summary>
        internal static string MTUShareTemplateWithAllUsers {
            get {
                return ResourceManager.GetString("MTUShareTemplateWithAllUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template.
        /// </summary>
        internal static string MTUTemplateFieldName {
            get {
                return ResourceManager.GetString("MTUTemplateFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DetailInfo.
        /// </summary>
        internal static string settingsListDetailInfoFieldName {
            get {
                return ResourceManager.GetString("settingsListDetailInfoFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EventType.
        /// </summary>
        internal static string settingsListEventTypeFieldName {
            get {
                return ResourceManager.GetString("settingsListEventTypeFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ItemID.
        /// </summary>
        internal static string settingsListItemIdFieldName {
            get {
                return ResourceManager.GetString("settingsListItemIdFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ListID.
        /// </summary>
        internal static string settingsListListIdFieldName {
            get {
                return ResourceManager.GetString("settingsListListIdFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CCSAdvancedAlertsList.
        /// </summary>
        internal static string settingsListName {
            get {
                return ResourceManager.GetString("settingsListName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner.
        /// </summary>
        internal static string settingsListOwner {
            get {
                return ResourceManager.GetString("settingsListOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebID.
        /// </summary>
        internal static string settingsListWebIdFieldName {
            get {
                return ResourceManager.GetString("settingsListWebIdFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WhenToSend.
        /// </summary>
        internal static string settingsListWhenToSendFieldName {
            get {
                return ResourceManager.GetString("settingsListWhenToSendFieldName", resourceCulture);
            }
        }
    }
}
