//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCSAdvancedAlerts {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class XMLElementNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal XMLElementNames() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CCSAdvancedAlerts.XMLElementNames", typeof(XMLElementNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BccAddress.
        /// </summary>
        internal static string BccAddress {
            get {
                return ResourceManager.GetString("BccAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IgnoredUsers.
        /// </summary>
        internal static string BlockedUsers {
            get {
                return ResourceManager.GetString("BlockedUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CcAddress.
        /// </summary>
        internal static string CcAddress {
            get {
                return ResourceManager.GetString("CcAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CombineAlerts.
        /// </summary>
        internal static string CombineAlerts {
            get {
                return ResourceManager.GetString("CombineAlerts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition.
        /// </summary>
        internal static string ConditionChildNodeName {
            get {
                return ResourceManager.GetString("ConditionChildNodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field.
        /// </summary>
        internal static string ConditionFieldTagName {
            get {
                return ResourceManager.GetString("ConditionFieldTagName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator.
        /// </summary>
        internal static string ConditionOperatorTagName {
            get {
                return ResourceManager.GetString("ConditionOperatorTagName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ComparisionType.
        /// </summary>
        internal static string ConditionsComparisionType {
            get {
                return ResourceManager.GetString("ConditionsComparisionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conditions.
        /// </summary>
        internal static string ConditionsRootNodeName {
            get {
                return ResourceManager.GetString("ConditionsRootNodeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string ConditionValueTagName {
            get {
                return ResourceManager.GetString("ConditionValueTagName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DailyBusinessDays.
        /// </summary>
        internal static string DailyBusinessDays {
            get {
                return ResourceManager.GetString("DailyBusinessDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DateColumn.
        /// </summary>
        internal static string DateColumnName {
            get {
                return ResourceManager.GetString("DateColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FromAddress.
        /// </summary>
        internal static string FromAddress {
            get {
                return ResourceManager.GetString("FromAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ImmediateAlways.
        /// </summary>
        internal static string ImmediateAlways {
            get {
                return ResourceManager.GetString("ImmediateAlways", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ImmediateBusinessDays.
        /// </summary>
        internal static string ImmediateBusinessDays {
            get {
                return ResourceManager.GetString("ImmediateBusinessDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ImmediateBusinessHoursFinish.
        /// </summary>
        internal static string ImmediateBusinessHoursFinish {
            get {
                return ResourceManager.GetString("ImmediateBusinessHoursFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ImmediateBusinessHoursStart.
        /// </summary>
        internal static string ImmediateBusinessHoursStart {
            get {
                return ResourceManager.GetString("ImmediateBusinessHoursStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PPosition.
        /// </summary>
        internal static string PPosition {
            get {
                return ResourceManager.GetString("PPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PQty.
        /// </summary>
        internal static string PQty {
            get {
                return ResourceManager.GetString("PQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PType.
        /// </summary>
        internal static string PType {
            get {
                return ResourceManager.GetString("PType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RCount.
        /// </summary>
        internal static string RCount {
            get {
                return ResourceManager.GetString("RCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat.
        /// </summary>
        internal static string Repeat {
            get {
                return ResourceManager.GetString("Repeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RInterval.
        /// </summary>
        internal static string RInterval {
            get {
                return ResourceManager.GetString("RInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RType.
        /// </summary>
        internal static string RType {
            get {
                return ResourceManager.GetString("RType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SendDay.
        /// </summary>
        internal static string SendDay {
            get {
                return ResourceManager.GetString("SendDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SendHour.
        /// </summary>
        internal static string SendHour {
            get {
                return ResourceManager.GetString("SendHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SummaryMode.
        /// </summary>
        internal static string SummaryMode {
            get {
                return ResourceManager.GetString("SummaryMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ToAddress.
        /// </summary>
        internal static string ToAddress {
            get {
                return ResourceManager.GetString("ToAddress", resourceCulture);
            }
        }
    }
}
